perception:
  image: __IMAGE__
  container_name: embodied-perception
  runtime: nvidia
  network_mode: host
  ipc: host
  pid: host
  privileged: true
  volumes:
    - /dev:/dev
    - /opt/embodied/models:/models
  environment:
    - ROS_DOMAIN_ID=42
    - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    - FASTRTPS_DEFAULT_PROFILES_FILE=/opt/phanthy-motus/config/fastdds_large_message.xml
  logging:
    driver: local
    options:
      max-size: "10m"
      max-file: "3"
  restart: unless-stopped
